# Workshop 1: Data cleaning and exploration 
*Anders Poirel and Oasys Okubo*
*30-09-2019*

First we import a few of the usual libraries used for data analysis in Python

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

Read in the data. Make sure the `.csv` file is in the same folder as this notebook.

In [2]:
data = pd.read_csv('registration_responses.csv')

## 1 Cleaning

Data acquired in the real world is rarely immediately fit for data analysis. Often, formatting and names will be inconsistent and there may be missing entries. In fact, data acquisition, cleaning and preparation is often reported to take >80% of the time of data scientists working in industry, so while it may be more boring than building models, it's an important skill to master.

As an example, we'll use the data we collected at Cornucopia:

In [3]:
data.head(15)

,Timestamp,Email Address,Name,Email,Phone number (xxx) xxx-xxxx,Major(s),Year
0,9/24/2019 11:46:12,rgdarlin@ucsc.edu,Ryan,rgdarlin@ucsc.edu,5305649868,Computational Math and Econ,Fourth Year
1,9/24/2019 11:46:19,apoirel@ucsc.edu,Anders Poirel,apoirel@ucsc.edu,(415) 324-9472,"Computer Science, Mathematics",Junior
2,9/24/2019 16:02:55,apoirel@ucsc.edu,Edwin,egarciah@ucsc.edu,510-334-6382,NaN,1st
3,9/24/2019 16:03:46,apoirel@ucsc.edu,David Park,mpark30@ucsc.edu,2133791363,cs,2023
4,9/24/2019 16:04:47,apoirel@ucsc.edu,Quinn Chalmers,qchalmer@ucsc.edu,6612998511,TIM,Senior
5,9/24/2019 16:06:43,apoirel@ucsc.edu,Eric Truong,ermtruon@ucsc.edu,(669) 265-9732,Computer Engineering,Second
6,9/24/2019 16:08:40,apoirel@ucsc.edu,nikhil sheth,npsheth@ucsc.edu,925-577-8542,Comp Sci,2020
7,9/24/2019 16:09:40,apoirel@ucsc.edu,Eugene Shin,eshin3@gmail.com,(650)922-0053,cs game design,Junior
8,9/24/2019 16:13:02,apoirel@ucsc.edu,Jason Yang,jyang206@ucsc.edu,5105987120,Computer Engineering,2023
9,9/24/2019 16:13:38,apoirel@ucsc.edu,Gopala,gnadadhu@ucsc.edu,8312972117,NaN,NaN
10,9/24/2019 16:15:11,apoirel@ucsc.edu,Navneet Pathak,napathak@ucsc.edu,(408) 219-2297,Computer Science,Frosh
11,9/24/2019 16:16:39,apoirel@ucsc.edu,Sanyam Sachdeva,ssachde3@ucsc.edu,5592876393,Computer Science,Junior
12,9/24/2019 16:17:24,apoirel@ucsc.edu,Balaram Behera,bbehera@ucsc.edu,5109363079,CS/math,3rd year (transfer)
13,9/24/2019 16:19:33,apoirel@ucsc.edu,Tim Zhang,yzhan596@ucsc.edu,5107899297,CS,Transfer Jr
14,9/24/2019 16:20:15,apoirel@ucsc.edu,Brian Duong,brianduong122333@gmail.com,9253517575,Computer Science,Transfer 1st year

In [4]:
data.tail(15)

,Timestamp,Email Address,Name,Email,Phone number (xxx) xxx-xxxx,Major(s),Year
164,NaN,NaN,Matt,mtjacobs@ucsc.edu,(408) 623-1752,NaN,NaN
165,NaN,NaN,Max Nakama,manakama@ucsc.edu,(510) 695-6425,NaN,NaN
166,NaN,NaN,Tyler,tkhun@ucsc.edu,(650) 288-7227,NaN,NaN
167,NaN,NaN,Aakaash Narayann,anaraya4@ucsc.edu,NaN,NaN,NaN
168,NaN,NaN,Joey Barcia,jbarcia@ucsc.edu,(805) 636-0702 ...,NaN,NaN
169,NaN,NaN,Brian Pereira,brpereir@ucsc.edu,(510) 686-0018,NaN,NaN
170,NaN,NaN,Jason Harpe,jaaharpe@ucsc.edu,(510) 372-6160,NaN,NaN
171,NaN,NaN,Richard Thai,rithai@ucsc.edu,NaN,NaN,NaN
172,NaN,NaN,Shreyas Ketkar,sketkar@ucsc.edu,NaN,NaN,NaN
173,NaN,NaN,Smeet Mehta,smsmetha@ucsc.edu,(831) 226-6555,NaN,NaN
174,NaN,NaN,Rafael Vanderzee,rvanderz@gmail.com,(661) 609-0069,NaN,NaN
175,NaN,NaN,Jason Li,jadli@ucsc.edu,(408) 691-7165\n,NaN,NaN
176,NaN,NaN,NaN,hmedina3@ucsc.edu,323-392-6317,NaN,NaN
177,NaN,NaN,NaN,estepro@ucsc.edu,NaN,NaN,NaN
178,NaN,NaN,Jeremy Gurganus,gurganusjeremy93@gmail.com,NaN,NaN,NaN

### 1.1  Major

We'll start by cleaning up the majors data. The below code reshapes the data to group it by major, selects only the `Major(s)` column and then aggregates using `count` to find how many times each category appears:

In [5]:
data.groupby('Major(s)')['Major(s)'].count()

Major(s)
AGPM                                         1
BME                                          4
Bio                                          1
Bioinformatics                               1
Biology                                      1
Biomolecular Engineering and Informatics     1
Business management economics                2
CE                                           6
CS                                          26
CS & Comp. Math                              1
CS BS                                        1
CS, Global Economics                         2
CS/math                                      1
CS: Game Design                              1
CSE                                          1
CSGD                                         1
Cognitive Science                            2
Cognitive science                            1
Comp Engineering                             1
Comp Sci                                     2
Comp math                                    1
Comp sci                                     1
Comp. SCIENCE                                1
CompSci                                      1
Computational Math and Econ                  1
Computer Engineering                         2
Computer Science                            21
Computer Science                             4
Computer Science & Stats minor               1
Computer Science Game Design                 1
                                            ..
Environmental Studies, Engineering           1
Math                                         2
Mathematics                                  1
Proposed TIM                                 1
Robotics                                     1
Statistical science                          1
TIM                                          6
Technology, Information & Management         1
Undeclared                                   1
applied Math                                 1
ce                                           1
cog sci                                      2
comp sci                                     1
compsci                                      1
computational mathematics                    1
computational media                          1
computer Science                             2
computer science                             5
computer science                             1
cs                                           7
cs game design                               1
declared sci-                                1
econ                                         1
econ with stats minor                        1
econ/math                                    1
f                                            1
mathematics                                  1
physics                                      1
psc.                                         1
undeclared math/science                      1
Name: Major(s), Length: 72, dtype: int64

We begin by filling in missing entries with "No response" (No answer can be a meaningful category of its own in many situations)

In [6]:
data = data.fillna('No response')

In [7]:
data.replace(to_replace = ['CS', 'CS BS', 'Comp sci', 'Comp Sci', 'CompSci',
                           'cs', 'comp sci', 'compsci', 'computer science', 'computer Science', 
                           'Comp. SCIENCE', 'computer science ', 'Computer Science and Engineering',
                           'cse', 'Computer Scince', 'Computer science', 'CSE', 'Computer Science ',
                           'Computer Science & Stats minor', 
                           'Computer Science, possible Robotics Engineering'
                          ],
    value = 'Computer Science',
    inplace = True)

In [8]:
data.replace(to_replace = ['ce', 'CE', 'Computer Engineering', 'Comp Engineering', 'ECE', 'Engineering'],
            value = 'Computer Engineering', inplace = True)

In [9]:
data.replace(to_replace = ['CS & Comp. Math' , 'CS/math', 'Computer Science, Mathematics'],
            value = 'Computer Science, Mathematics', inplace = True)

In [10]:
data.replace(to_replace = ['Comp math', 'Math', 'Mathematics', 'mathematics', 'applied math',
                          'applied Math', 'computational mathematics'],
            value = 'Mathematics', inplace = True)

In [11]:
data.replace(to_replace = ['CS: Game Design', 'CSGD', 'cs game design', 'Computer Science Game Design'],
            value = 'Computer Science: Game Design', inplace = True)

In [12]:
data.replace(to_replace = ['Cognitive Science', 'Cognitive science', 'cog sci'],
             value = 'Cognitive Science', inplace = True)

In [13]:
data.replace(to_replace = ['Econ+Math', 'econ/math', 'Computational Math and Econ'], 
             value = 'Mathematics, Economics',
             inplace = True)

In [14]:
data.replace(to_replace = ['Computer Science/Cog Sci', 'Computer Science and Artificial Intelligence', 
                          'Computer Science and Cognitive Science '],
             value = 'Cognitive Science, Computer Science', inplace = True)

In [15]:
data.replace(to_replace = ['Business management economics','econ', 'econ with stats minor'],
            value = 'Economics', inplace = True)

In [16]:
data.replace(to_replace = ['BME', 'Biomolecular Engineering and Informatics'],
            value = 'Biomolecular Engineering', inplace = True)

In [17]:
data.replace(to_replace = ['TIM', 'Proposed TIM', 'Technology, Information & Management'],
            value = 'Technology, Information & Management', inplace = True)

In [18]:
data.replace(to_replace = ['undeclared math/science'], value = 'Undeclared', inplace = True)

In [19]:
data.replace(to_replace = ['Bio'], value = 'Biology', inplace = True)

Cleaning up the remaining entries using the dictionary syntax for `replace`:

In [20]:
data.replace(to_replace = {
    'Economics, TIM': 'Ecomomics, Technology, Information & Management',
    'computational media' : 'Computational Media',
    'physics ' : 'Physics',
    'f' : 'No response',
    'declared sci-' : 'No response',
    'psc.' : 'Psychology',
    'CS, Global Economics' : 'Computer Science, Economics'
}, inplace = True)

In [21]:
data.groupby('Major(s)')['Major(s)'].count()

Major(s)
AGPM                                                1
Bioinformatics                                      1
Biology                                             2
Biomolecular Engineering                            5
Cognitive Science                                   5
Cognitive Science, Computer Science                 3
Computational Media                                 1
Computer Engineering                               12
Computer Science                                   80
Computer Science, Economics                         2
Computer Science, Mathematics                       3
Computer Science: Game Design                       4
Ecomomics, Technology, Information & Management     1
Economics                                           4
Environmental Studies, Engineering                  1
Mathematics                                         7
Mathematics, Economics                              3
No response                                        30
Physics                                             1
Psychology                                          1
Robotics                                            1
Statistical science                                 1
Technology, Information & Management                8
Undeclared                                          2
Name: Major(s), dtype: int64

### 1.2 Year

Like before, we want to see what are all the different categories of entries for `Year`

In [22]:
data.groupby('Year')['Year'].count()

Year
!st                        1
1                          9
1st                        9
1st year                   1
2                         13
2000                       1
2019                       1
2020                       5
2021                       3
2022                       8
2023                      19
22                         1
2nd                        5
2rd                        2
3                         11
3rd                        6
3rd year                   1
3rd year (transfer)        1
4                          1
4th                        9
FROSH                      1
First                      1
First Year                 1
Fourth Year                1
Freshman                   2
Freshman                   1
Freshman year. (2019)      1
Frosh                      2
Grad 2020                  1
Grad MS                    1
Jr                         1
Junior                     8
Junior                     1
No response               30
Second                     1
Senior                     3
Sophomore                  2
Third                      1
Transfer                   2
Transfer 1st year          1
Transfer Jr                1
c/o 2023                   1
fourth                     1
freshman                   1
frosh                      1
grad                       1
j                          1
junior                     1
senior                     1
sophomore                  1
Name: Year, dtype: int64

What we did above gets really tedious We''l use the fancier way of finding and replacing entries using regular expressions. Notice that we could very well hardcode all of this with `data.replace` if we wanted.

In [23]:
import re
for d, i in enumerate(data['Year']):
    if re.search('fr|fir|2023|1st|1', i, re.IGNORECASE):
        data['Year'][d] = 'Freshman'
    elif re.search('sop|sec|2022|2nd|2|22', i, re.IGNORECASE):
        data['Year'][d] = 'Sophomore'
    elif re.search('jun|thi|2021|3rd|3|jr|j|tran', i, re.IGNORECASE):
        data['Year'][d] = 'Junior'
    elif re.search('sen|fou|2020|4|4th', i, re.IGNORECASE):
        data['Year'][d] = 'Senior'
    elif re.search('gra', i, re.IGNORECASE):
        data['Year'][d] = 'Graduate'

Alternatively, we could pass the regex directly into the pandas `replace`.

In [24]:
data.replace(to_replace = '!st', value = 'Freshman', inplace = True)

In [25]:
data.groupby('Year')['Year'].count()

Year
Freshman       56
Graduate        2
Junior         35
No response    30
Senior         16
Sophomore      40
Name: Year, dtype: int64

### 1.3 Phone numbers

In [26]:
data['Area'] = [np.nan for i in range(0, data.shape[0])]

In [27]:
for d, i in enumerate(data['Phone number (xxx) xxx-xxxx']):
    if i is not "No response":
        new_num = re.sub("\D", "", i)
        if len(new_num) is 10: # Check if it phone number is length of 10
            newid = '(' +new_num[0:3] + ') ' + new_num[3:6] + "-" + new_num[6:10]
            data['Phone number (xxx) xxx-xxxx'][d] = newid
            data['Area'][d] = new_num[0:3]
        else: # Otherwise, there may be an area code or invalid phone number
            data['Phone number (xxx) xxx-xxxx'][d] = 'No response'

C:\Users\Anders\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\Anders\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys
C:\Users\Anders\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

Now that we have numbers we can extract geographical location from the area code:

In [28]:
data.head(20)

,Timestamp,Email Address,Name,Email,Phone number (xxx) xxx-xxxx,Major(s),Year,Area
0,9/24/2019 11:46:12,rgdarlin@ucsc.edu,Ryan,rgdarlin@ucsc.edu,(530) 564-9868,"Mathematics, Economics",Senior,530.0
1,9/24/2019 11:46:19,apoirel@ucsc.edu,Anders Poirel,apoirel@ucsc.edu,(415) 324-9472,"Computer Science, Mathematics",Junior,415.0
2,9/24/2019 16:02:55,apoirel@ucsc.edu,Edwin,egarciah@ucsc.edu,(510) 334-6382,No response,Freshman,510.0
3,9/24/2019 16:03:46,apoirel@ucsc.edu,David Park,mpark30@ucsc.edu,(213) 379-1363,Computer Science,Freshman,213.0
4,9/24/2019 16:04:47,apoirel@ucsc.edu,Quinn Chalmers,qchalmer@ucsc.edu,(661) 299-8511,"Technology, Information & Management",Senior,661.0
5,9/24/2019 16:06:43,apoirel@ucsc.edu,Eric Truong,ermtruon@ucsc.edu,(669) 265-9732,Computer Engineering,Sophomore,669.0
6,9/24/2019 16:08:40,apoirel@ucsc.edu,nikhil sheth,npsheth@ucsc.edu,(925) 577-8542,Computer Science,Sophomore,925.0
7,9/24/2019 16:09:40,apoirel@ucsc.edu,Eugene Shin,eshin3@gmail.com,(650) 922-0053,Computer Science: Game Design,Junior,650.0
8,9/24/2019 16:13:02,apoirel@ucsc.edu,Jason Yang,jyang206@ucsc.edu,(510) 598-7120,Computer Engineering,Freshman,510.0
9,9/24/2019 16:13:38,apoirel@ucsc.edu,Gopala,gnadadhu@ucsc.edu,(831) 297-2117,No response,No response,831.0
10,9/24/2019 16:15:11,apoirel@ucsc.edu,Navneet Pathak,napathak@ucsc.edu,(408) 219-2297,Computer Science,Freshman,408.0
11,9/24/2019 16:16:39,apoirel@ucsc.edu,Sanyam Sachdeva,ssachde3@ucsc.edu,(559) 287-6393,Computer Science,Junior,559.0
12,9/24/2019 16:17:24,apoirel@ucsc.edu,Balaram Behera,bbehera@ucsc.edu,(510) 936-3079,"Computer Science, Mathematics",Junior,510.0
13,9/24/2019 16:19:33,apoirel@ucsc.edu,Tim Zhang,yzhan596@ucsc.edu,(510) 789-9297,Computer Science,Junior,510.0
14,9/24/2019 16:20:15,apoirel@ucsc.edu,Brian Duong,brianduong122333@gmail.com,(925) 351-7575,Computer Science,Freshman,925.0
15,9/24/2019 16:29:05,apoirel@ucsc.edu,Matt Atiqi,matiqi@ucsc.edu,(925) 309-9550,"Technology, Information & Management",Freshman,925.0
16,9/24/2019 16:29:47,apoirel@ucsc.edu,samuel indurkar,sindurka@ucsc.edu,(408) 508-1721,Computer Engineering,Sophomore,408.0
17,9/24/2019 16:31:37,apoirel@ucsc.edu,Noah West,nolwest@ucsc.edu,(661) 340-3539,Computer Science,Junior,661.0
18,9/24/2019 16:32:52,apoirel@ucsc.edu,Jake,jelliot1@ucsc.edu,(424) 280-0203,Computer Engineering,Freshman,424.0
19,9/24/2019 16:34:13,apoirel@ucsc.edu,Swetha Thiru,sthiru@ucsc.edu,(510) 770-4337,Computer Science: Game Design,Freshman,510.0

#### 1.3.1 Region extraction
To extract location information from area codes we'll need to use another dataset. This will be good practice in combining datasets!.

The second dataset we'll use is is table of cities with associated area codes:

(https://github.com/ravisorg/Area-Code-Geolocation-Database/blob/master/us-area-code-cities.csv)[https://github.com/ravisorg/Area-Code-Geolocation-Database/blob/master/us-area-code-cities.csv]

In [43]:
area_loc = pd.read_csv('us-area-code-cities.csv', header = None)

array([0, 1, 2, 3, 4, 5], dtype=int64)

In [44]:
area_loc.head()

     0               1           2   3         4         5
0  201         Bayonne  New Jersey  US  40.66871 -74.11431
1  201     Bergenfield  New Jersey  US  40.92760 -73.99736
2  201  Cliffside Park  New Jersey  US  40.82149 -73.98764
3  201       Englewood  New Jersey  US  40.89288 -73.97264
4  201       Fair Lawn  New Jersey  US  40.94038 -74.13181

We drop superfluous columns with geographical coordinates:

In [49]:
area_loc.drop([3,4,5], axis = 1, inplace = True)

In [50]:
area_loc.rename(columns =  {0:'Code', 1:'City', 2:'State'})

      Code                City                 State
0      201             Bayonne            New Jersey
1      201         Bergenfield            New Jersey
2      201      Cliffside Park            New Jersey
3      201           Englewood            New Jersey
4      201           Fair Lawn            New Jersey
5      201            Fort Lee            New Jersey
6      201          Hackensack            New Jersey
7      201             Hoboken            New Jersey
8      201         Jersey City            New Jersey
9      201              Kearny            New Jersey
10     201        North Bergen            New Jersey
11     201             Paramus            New Jersey
12     201           Ridgewood            New Jersey
13     201             Teaneck            New Jersey
14     201          Union City            New Jersey
15     201       West New York            New Jersey
16     202          Washington  District of Columbia
17     203          Bridgeport           Connecticut
18     203             Danbury           Connecticut
19     203          East Haven           Connecticut
20     203             Meriden           Connecticut
21     203             Milford           Connecticut
22     203           Naugatuck           Connecticut
23     203           New Haven           Connecticut
24     203         North Haven           Connecticut
25     203             Norwalk           Connecticut
26     203             Shelton           Connecticut
27     203            Stamford           Connecticut
28     203           Stratford           Connecticut
29     203            Trumbull           Connecticut
...    ...                 ...                   ...
2736   980      South Gastonia        North Carolina
2737   980        Huntersville        North Carolina
2738   980          Kannapolis        North Carolina
2739   980            Matthews        North Carolina
2740   980              Monroe        North Carolina
2741   980           Salisbury        North Carolina
2742   980         Statesville        North Carolina
2743   984                Apex        North Carolina
2744   984                Cary        North Carolina
2745   984         Chapel Hill        North Carolina
2746   984              Durham        North Carolina
2747   984           Goldsboro        North Carolina
2748   984        West Raleigh        North Carolina
2749   984             Sanford        North Carolina
2750   985               Houma             Louisiana
2751   985             Laplace             Louisiana
2752   985             Slidell             Louisiana
2753   989            Bay City              Michigan
2754   989             Midland              Michigan
2755   989      Mount Pleasant              Michigan
2756   989             Saginaw              Michigan
2757   989             Saginaw              Michigan
2758   854    North Charleston        South Carolina
2759   854            Florence        South Carolina
2760   854         Goose Creek        South Carolina
2761   854  Hilton Head Island        South Carolina
2762   854      Mount Pleasant        South Carolina
2763   854  North Myrtle Beach        South Carolina
2764   854    North Charleston        South Carolina
2765   854         Summerville        South Carolina

[2766 rows x 3 columns]

Group along area codes:

KeyError: 'Level Code must be same as name (None)'

## 2 Exploration

In [30]:
plt.style.use('seaborn')